### ISSUE TITLE
no dependencies in package.json

### ISSUE THREAD

**Issue by fbrisola** [tpg/vitamin#4]
Everytime I install this, the package.json ends with only scripts and no dependencies. Is this the expected behavior?

//package.json
"scripts": {
        "dev": "php ./artisan vitamin:serve",
        "production": "vite build",
        "prod": "yarn production",
        "routes": "php ./artisan ziggy:generate resources/js/routes.js",
        "horizon": "php ./artisan horizon"
    },
    "dependencies": {}
}

**Comment by warrickbayman** [comment]
Thanks for spotting this. Completely snuck by me. Fixed in 0.5.1.

**Comment by fbrisola** [comment]
Glad to help!
