### ISSUE TITLE
Ziggy Resource Route Issue

### ISSUE THREAD

**Issue by JD456976** [tpg/vitamin#8]
Hello,

Thank you for all your work. I came across your package when looking at Vite itself.  

Having an issue with Ziggy and resource routes, and I'm sure it's on my end.  

I have a resource route named: 

```
Route::resource('test', HomeController::class);
```
Where the index method returns a Vue component named Test.vue directly in the Pages folder.  

Test.vue:
```
<template>
Hello tester!!
    <a :href=route('test.index')>test</a>
</template>

<script setup>
import {route} from '@/Scripts/Routing/Router.js'
export default {
    name: "Test",
}
</script>

<style scoped>

</style>
```

However, if I try to load that page, I get this error:

```
[plugin:vite:vue] Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (`).


1  |  <template>
2  |  Hello tester!!
3  |      <a :href=route('test.index')>test</a>
   |                      ^
4  |  </template>
5  |
```

I'm perplexed as to what I'm missing or if there's an actual issue.

**Comment by warrickbayman** [comment]
Thanks for the compliments. 
Your attribute value needs to be quoted. So:

```
<a :href="route('test.index')">test</a>
```
